DoAn_ASPNETCORE/Views/SmartPhoneViewComponent.cs
using DoAn_ASPNETCORE.Areas.Admin.Data;
using DoAn_ASPNETCORE.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace DoAn_ASPNETCORE.ViewComponents
{
    [ViewComponent(Name = "SmartPhone")]
    public class SmartPhoneViewComponent:ViewComponent
    {
        private readonly Webbanhang db;
        public SmartPhoneViewComponent(Webbanhang context)
        {
            db = context;
        }
        public async Task<IViewComponentResult> InvokeAsync(
        int id)
        {
            string MyView = "Smartphone";
           
            var items = await LaySanPham(id);

            return View(MyView, items);
        }
        private Task<List<SanPhamModel>> LaySanPham(int id)
        {
            return db.SanPhamModel.Where(x => x.MaLoai == id).ToListAsync();
        }
    }

}

DoAn_ASPNETCORE/Views/Pages/Cart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<DoAn_ASPNETCORE.Areas.Admin.Models.ItemModel>

<h2><center>CART</center></h2>

@if (Model.Count > 0)
{
    decimal total = 0;
    int stt = 1;

    <table class="table">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Image</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th></th>
        </tr>
        @foreach (var cartitem in Model)
        {
            var thanhtien = cartitem.Quantity * cartitem.SanPham.Gia;
            total += thanhtien;

            <tr>
                <td>@(stt++)</td>
                <td>@cartitem.SanPham.TenSP</td>
                <td> <img src="~/images/@cartitem.SanPham.Image" style="height:200px" class="img-responsive" alt=""></td>
                <td>@(cartitem.SanPham.Gia.ToString("n0"))</td>
                <td><input asp-for="@cartitem.Quantity" id="@($"quantity-{cartitem.SanPham.ID}")" /></td>
                <td>@(thanhtien.ToString("n0"))</td>
                <td>
                    <button class="btn btn-success updatecartitem"
                            data-productid="@cartitem.SanPham.ID">
Update
                    </button>
                    <a asp-route="removecart" asp-route-productid="@cartitem.SanPham.ID"
                       class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
        
    </table>

    <a asp-controller="Pages" asp-action="Checkout" class="btn btn-success">Checkout</a>

    @section Scripts {
        <script>
          $(document).ready(function () {
              $(".updatecartitem").click(function (event) {
                  event.preventDefault();
                  var productid = $(this).attr("data-productid");
                  var quantity = $("#quantity-" + productid).val();
                  $.ajax({
                      type: "POST",
                      url:"@Url.RouteUrl("updatecart")",
                      data: {
                          productid: productid,
                          quantity:quantity
                      },
                      success: function (result) {
                          window.location.href = "@Url.RouteUrl("cart")";
                      }
                  });
              });
          });
        </script>
    }

}
else
{
<p class="alert alert-danger">
    Your cart is empty
</p>
}

DoAn_ASPNETCORE/Views/Pages/Index.cshtml
@model IEnumerable<DoAn_ASPNETCORE.Areas.Admin.Models.SanPhamModel>
@{
    ViewData["Title"] = "pages Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--banner-->
<div class="banner-w3">
    <div class="demo-1">
        <div id="example1" class="core-slider core-slider__carousel example_1">
            <div class="core-slider_viewport">
                <div class="core-slider_list">
                    <div class="core-slider_item">
                        <img src="~/images/b3.png" class="img-responsive" alt="">
                    </div>
                    <div class="core-slider_item">
                        <img src="~/images/b4.png" class="img-responsive" alt="">
                    </div>
                </div>
            </div>
            <div class="core-slider_nav">
                <div class="core-slider_arrow core-slider_arrow__right"></div>
                <div class="core-slider_arrow core-slider_arrow__left"></div>
            </div>
            <div class="core-slider_control-nav"></div>
        </div>
    </div>
    <link href="~/user/css/coreSlider.css" rel="stylesheet" type="text/css">
    <script src="~/user/js/coreSlider.js"></script>
    <script>
        $('#example1').coreSlider({
            pauseOnHover: false,
            interval: 3000,
            controlNavEnabled: true
        });

    </script>

</div>
<!--banner-->
<!--content-->
<div class="content">
    <!--banner-bottom-->
    <div class="ban-bottom-w3l">
        <div class="container">
            <div class="col-md-6 ban-bottom">
                <div class="ban-top">
                    <img src="~/images/p1s.png" class="img-responsive" alt="" />
                    <div class="ban-text">
                        <h4>Magsafe Charge</h4>
                    </div>
                    <div class="ban-text2 hvr-sweep-to-top">
                        <h4>50% <span>Off/-</span></h4>
                    </div>
                </div>
            </div>
            <div class="col-md-6 ban-bottom3">
                <div class="ban-top">
                    <img src="~/images/p2s.png" class="img-responsive" alt="" />
                    <div class="ban-text1">
                        <h4>AirPod Pro</h4>
                    </div>
                </div>
                <div class="ban-img">
                    <div class=" ban-bottom1">
                        <div class="ban-top">
                            <img src="~/images/p3s.jpg" class="img-responsive" alt="" />
                            <div class="ban-text1">
                                <h4>APPLE WATCH SERIES 6</h4>
                            </div>
                        </div>
                    </div>
                    <div class="ban-bottom2">
                        <div class="ban-top">
                            <img src="~/images/p4s.jpg" class="img-responsive" alt="" />
                            <div class="ban-text1">
                                <h4>bUDS LIVE</h4>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!--banner-bottom-->
    <!--new-arrivals-->
    @await Component.InvokeAsync("Index", new { id = "DM1" })
    <!--new-arrivals-->
    <!--accessories-->
    <!--Products-->
    @await Component.InvokeAsync("Index", new { id = "DM2" })
    <!--Products-->
    @await Component.InvokeAsync("Index", new { id = "DM3" })
    <!--new-arrivals-->
</div>
<!--content-->
<!--new-arrivals-->
        </div>
<!--content-->

DoAn_ASPNETCORE/Views/Pages/checkout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model DoAn_ASPNETCORE.Areas.Admin.Models.HoaDonModel
@{
    ViewData["Title"] = "pages Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--banner-->
<div id="successModal" class="modal fade">
    <div class="modal-dialog modal-confirm">
        <div class="modal-content">
            <div class="modal-header">
                <div class="icon-box">
                    <i class="material-icons">&#xE876;</i>
                </div>
                <h4 class="modal-title w-100">Thêm Thành Công!</h4>
            </div>
            <div class="modal-footer">
                <button type="button" style="margin-left:90px;" name="btn_ok" class="btn btn-success btn-block" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>
<div class="banner1">
    <div class="container">
        <h3><a asp-area="" asp-controller="Home" asp-action="Index">Home</a> / <span>Checkout</span></h3>
    </div>
</div>
<div class="content">
    <div class="cart-items">
        <div class="container">
            <h2>Đơn Hàng Của Tôi</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Hình Ảnh</th>
                        <th>Tên SP</th>
                        <th>Số Lượng</th>
                        <th>Giá Bán</th>
                        <th>Tổng cộng</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        long tongtien = 0;
                        string TenSP = "";
                        int size = ViewBag.size;
                        int i = 0;
                        string sl = "";
                        string gia = "";

                    }
                    @foreach (var item in ViewBag.cart)
                    {
                        i++;
                        long tongcong = @item.SanPham.GiaMoi * @item.Quantity;
                        tongtien += tongcong;

                        if (i == size)
                        {
                            sl += @item.Quantity;
                            TenSP += @item.SanPham.TenSP;
                            gia += @item.SanPham.GiaMoi;
                        }
                        else
                        {
                            TenSP += @item.SanPham.TenSP + "/";
                            sl += @item.Quantity + "/";
                            gia += @item.SanPham.GiaMoi + "/";
                        }

                        <tr>
                            <td>
                                <img src="~/images/@item.SanPham.Image " class="img-thumbnail" style="width:10%" alt="">
                            </td>
                            <td>
                                <h3><a href="#">@item.SanPham.TenSP </a></h3>
                            </td>
                            <td>
                                @item.Quantity
                            </td>
                            <td>
                                @item.SanPham.GiaMoi.ToString("n0") VND
                            </td>
                            <td>
                                @tongcong.ToString("n0") VND
                            </td>
                        </tr>

                    }
                    <tr>
                        <td colspan="5">
                            <h4><b>Tổng tiền :  @tongtien.ToString("n0") VND</b></h4>
                        </td>
                    </tr>
                </tbody>
            </table>
            <p>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Checkout">Tiếp Tục</button>
            </p>
        </div>
    </div>
</div>
<div class="modal fade" id="Checkout" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <center><h3 class="modal-title" id="exampleModalLabel">THÔNG TIN ĐẶT HÀNG</h3></center>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-area="Admin" asp-controller="HoaDon" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="User_ID" class="control-label"></label>
                        <input asp-for="User_ID" value="@ViewBag.id" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="HoTen" class="control-label"></label>
                        <input asp-for="HoTen" class="form-control" />
                        <span asp-validation-for="HoTen" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Sdt" class="control-label"></label>
                        <input asp-for="Sdt" class="form-control" />
                        <span asp-validation-for="Sdt" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ThanhTien" class="control-label"></label>
                        <input asp-for="ThanhTien" value="@tongtien" readonly class="form-control" />
                    </div>
                    <div class="form-group">
                        <label class="control-label">Bạn có mã khuyến mãi?</label>
                        <input type="text" name="KhuyenMai" class="form-control" />
                    </div>
                    <input value="@TenSP" name="TenSP" />
                    <input value="@sl" name="SoLuong" />
                    <input value="@gia" name="Gia" />
                    <input value="1" name="TrangThai" />
                    <div class="form-group">
                        <input type="submit" value="DatHang" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>

            </div>

        </div>
    </div>
</div>

DoAn_ASPNETCORE/Views/Pages/login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!--banner-->
<div class="banner1">
    <div class="container">
        <h3><a asp-area="" asp-controller="Home" asp-action="Index">Home</a> / <span>Login</span></h3>
    </div>
</div>
<!--banner-->
<!--content-->
<div class="content">
    <!--login-->
    <!--<div class="login">
        <div class="main-agileits">
            <div class="form-w3agile">
                <h3>Login To New Shop</h3>
                <form action="#" method="post">
                    <div class="key">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                        <input type="text" value="Email" name="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
                        <div class="clearfix"></div>
                    </div>
                    <div class="key">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                        <input type="password" value="Password" name="Password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}" required="">
                        <div class="clearfix"></div>
                    </div>
                    <input type="submit" value="Login">
                </form>
            </div>
            <div class="forg">
                <a href="#" class="forg-left">Forgot Password</a>
                <a href="~/user/pages/registered" class="forg-right">Register</a>
                <div class="clearfix"></div>
            </div>
            <div id="fb-root">
        </div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v9.0&appId=250620996446716&autoLogAppEvents=1" nonce="P7yrjRmc"></script>-->
    @*@<div class="fb-login-button" data-width="" data-size="large" data-button-type="continue_with" data-layout="default" data-auto-logout-link="false" data-use-continue-as="false"></div>*@
    <!--<fb:login-button scope="public_profile,email"
                    onlogin="checkLoginState();">
        </fb:login-button>
    </div>

    </div>-->
    @await Component.InvokeAsync("Login")

    <!--login-->
</div>

DoAn_ASPNETCORE/Views/Pages/mail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!--banner-->
<div class="banner1">
    <div class="container">
        <h3><a href="~/user/pages/index">Home</a> / <span>Mail Us</span></h3>
    </div>
</div>
<!--banner-->
<!--content-->
<div class="content">
    <!--contact-->
    <div class="mail-w3ls">
        <div class="container">
            <h2 class="tittle">Mail Us</h2>
            <div class="mail-grids">
                <div class="mail-top">
                    <div class="col-md-4 mail-grid">
                        <i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>
                        <h5>Address</h5>
                        <p>9th floor - Palace Building - 221B Walk of Fame - USA</p>
                    </div>
                    <div class="col-md-4 mail-grid">
                        <i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>
                        <h5>Phone</h5>
                        <p>Telephone:  +1 800 603 6035</p>
                    </div>
                    <div class="col-md-4 mail-grid">
                        <i class="glyphicon glyphicon-envelope" aria-hidden="true"></i>
                        <h5>E-mail</h5>
                        <p>E-mail:<a href="mailto:example@mail.com"> example@mail.com</a></p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="map-w3">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d673607.6340751307!2d-104.44001811743372!3d48.738351336759585!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5321f600f5170943%3A0x94f2e8e71e1dfc7a!2sE+Comertown+Rd%2C+Westby%2C+MT+59275%2C+USA!5e0!3m2!1sen!2sin!4v1467080368135" allowfullscreen></iframe>
                </div>
                <div class="mail-bottom">
                    <h4>Get In Touch With Us</h4>
                    <form action="#" method="post">
                        <input type="text" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}" required="">
                        <input type="email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
                        <input type="text" value="Telephone" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Telephone';}" required="">
                        <textarea onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Message...</textarea>
                        <input type="submit" value="Submit">
                        <input type="reset" value="Clear">

                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--contact-->
</div>
<!--content-->

DoAn_ASPNETCORE/Views/Pages/products.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!--banner-->
<div class="banner1">
    <div class="container">
        <h3><a href="~/pages/index">Home</a> / <span>Smartphones</span></h3>
    </div>
</div>
<!--banner-->
<!--content-->
<div class="content">
    <div class="products-agileinfo">
        <h2 class="tittle">SMARTPHONE</h2>
        <div class="container">
            <div class="product-agileinfo-grids w3l">
                <div class="col-md-3 product-agileinfo-grid">
                    <div class="categories">
                        <h3>Categories</h3>
                        <ul class="tree-list-pad">
                            <li>
                                @*<input type="checkbox" checked="checked" id="item-0" /><label for="item-0"><span></span></label>*@
                                <ul>
                                   
                                            <li><a href="products.html">Samsung</a></li>
                                            <li><a href="products.html">iPhone</a></li>                                           
                                                                           
                                </ul>
                            </li>
                            
                        </ul>
                    </div>
                    
                    
                    
                    <div class="cat-img">
                        <img class="img-responsive " src="~/images/45.jpg" alt="">
                    </div>
                </div>
                <div class="col-md-9 product-agileinfon-grid1 w3l">
                    
                    <div class="mens-toolbar">
                        
                        <div class="clearfix"></div>
                    </div>


                    @*<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class="nav1 nav1-tabs left-tab" role="tablist">
                            <ul id="myTab" class="nav nav-tabs left-tab" role="tablist">
                                <li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true"><img src="~/images/menu1.png"></a></li>
                                <li role="presentation"><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile"><img src="~/images/menu.png"></a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
                                    <div class="product-tab">

                                        @foreach (var item in ViewBag.Loai)
                                        {
                                            <div class="col-md-4 product-tab-grid simpleCart_shelfItem">
                                                <div class="grid-arr">
                                                    <div class="grid-arrival">
                                                        <figure>
                                                            <a href="~/pages/single/@item.ID">
                                                                <div class="grid-img">
                                                                    <img src="~/images/@item.Image" class="img-responsive" alt="">
                                                                </div>
                                                                <div class="grid-img">
                                                                    <img src="~/images/@item.Image" class="img-responsive" alt="">
                                                                </div>
                                                            </a>
                                                        </figure>
                                                    </div>
                                                    <div class="block">
                                                        <div class="starbox small ghosting"> </div>
                                                    </div>
                                                    <div class="women">
                                                        <h6><a href="~/pages/single">@item.TenSP</a></h6>
                                                        <span class="size">XL / XXL / S </span>
                                                        <p><del>@item.Gia</del><em class="item_price">@item.GiaMoi</em></p>
                                                        <a href="~/Pages/detail/@item.ID" data-text="Add To Cart" class="my-cart-b item_add">Add To Cart</a>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                
                                        <div class="clearfix"></div>
                                    </div>

                                </div>
                            </div>
                    </div>*@
                    @await Component.InvokeAsync("SmartPhone",new {id=ViewBag.id})

                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
</div>
<!--content-->

DoAn_ASPNETCORE/Views/Pages/registered.cshtml
<div class="banner1">
    <div class="container">
        <h3><a href="~/user/pages/index">Home</a> / <span>Registered</span></h3>
    </div>
</div>
<!--banner-->
<!--content-->
<div class="content">
    <!--login-->
    <div class="login">
        <div class="main-agileits">
            <div class="form-w3agile form1">
                <h3>Register</h3>
                <form action="#" method="post">
                    <div class="key">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <input type="text" value="Username" name="Username" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Username';}" required="">
                        <div class="clearfix"></div>
                    </div>
                    <div class="key">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                        <input type="text" value="Email" name="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
                        <div class="clearfix"></div>
                    </div>
                    <div class="key">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                        <input type="password" value="Password" name="Password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}" required="">
                        <div class="clearfix"></div>
                    </div>
                    <div class="key">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                        <input type="password" value="Confirm Password" name="Confirm Password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Confirm Password';}" required="">
                        <div class="clearfix"></div>
                    </div>
                    
                    <input type="submit" value="Submit">
                </form>
            </div>

        </div>
    </div>
    <!--login-->
</div>
<!--content-->